@base=http://localhost:5000/api
@patient_access=Bearer


### Register a patient...
POST {{base}}/patient/register
Content-Type: application/json

{
  "name": "Gerard Nwazk",
  "email": "gnwazk@gmail.com",
  "phone_number": "08186612324",
  "password": "Pass=123"
}


### Login a patient...
POST {{base}}/patient/login
Content-Type: application/json

{
  "email": "gnwazk@gmail.com",
  "password": "Pass=123"
}


### Add next of kin...
POST {{base}}/patient/add-next-of-kin
Content-Type: application/json
Authorization: {{patient_access}}

{
  "name": "Chinasa Nwazk",
  "email": "cynthiachuks@gmail.com",
  "phone_number": "08038363914",
  "relationship": "Wife"
}


### Update Profile...
POST {{base}}/patient/profile
Content-Type: application/json
Authorization: {{patient_access}}

{
  "dob": "1990-11-18",
  "gender": "Male",
  "address": "123 Main St"
}

